%YAML:1.0

ImageFilesPath: /data/标定数据/上海小车/2号/20231120/1/lidar_baselink/predata/img
LiDARFilesPath: /home/user/data/flashbot

CamsIntrinsicPath: /data/标定数据/上海小车/2号/20231120/1/zros_files/data/flashbot_002_dropngo3.0/component/camera
CamsExtrinsicPath: /data/标定数据/上海小车/2号/20231120/1/2号_1120_camera&lidar外参/camera

SceneNum: 1

init_extrinsic_file: /home/user/data/flashbot/init_transform_dr_front.pb.txt
result_path:  /home/user/data/flashbot/result

CameraName:
  - avm_front
  - avm_left
  - avm_rear
  - avm_right


Canny.gray_threshold: 10
Canny.len_threshold: 50

# Params for Voxel Cutting & Plane Fitting & Edge Extraction
Voxel.size: 2
Voxel.eigen_ratio: 0.05
Voxel.down_sample_size: 0.02
Plane.min_points_size: 100
Plane.normal_theta_min: 30
Plane.normal_theta_max: 160
Plane.max_size: 8
Ransac.dis_threshold: 0.02
Edge.min_dis_threshold: 0.08


# Params for color point clouds
Color.dense: 0.1
Color.intensity_threshold: 5

# 0:p2p, 1:p2line
match_type: 1

update_camera_extrinsic: 1
use_ground_lines: 1
save_lidar_extrinsic_name: roof_transform.pb.txt

img_file_extension: bmp
