%YAML:1.0

BaseLidar:
  pcds_file: /mount_dir/lam_data/calibration_jira/DG_0725/pcd
  max_dis: 40
  min_dis: 1
  # hesai64, bp32, helios32, ft120, yijing
  lidar_type: ft120 
  tz: 1.2

RefNum: 0
Step: 5
SceneNum: 3
ThTime: 3

ShowResidual: 0
UseCADPrior: 1

DrPosesFile: /home/wd/datasets/FT120/flashbot-2131/dr_tum.txt
AroundCameraStampFile: /media/lam_data/calibration_jira/FLASHBOT-2131/video/24-04-22_10-56-42_656/video/video_frame_info
ImageFilesPath: /media/lam_data/calibration_jira/FLASHBOT-2131/video/24-04-22_10-56-42_656/jpg
CamsIntrinsicPath: /media/lam_data/calibration_jira/DG_0725/camera_baselink/camera
CamsExtrinsicPath: /media/lam_data/calibration_jira/DG_0725/camera_baselink/camera
LidarExtrinsicFile: /home/wd/projects/calib_tools/dr_lidar_calib_ws/src/dr_lidar_calib/assets/CarModels/CN01/lidar/roof_front_transform.pb.txt

SaveLidarExtrinsicName: roof_front_transform.pb.txt
ResultPath:  /home/wd/datasets/FT120/RESULT

#####
CameraName:
  - avm_front
  - avm_left
  - avm_rear
  - avm_right
  # - front_near
  # - left_front
  # - left_rear
  # - rear_medium
  # - right_front
  # - right_rear

Canny.gray_threshold: 10
Canny.len_threshold: 50

# Params for Voxel Cutting & Plane Fitting & Edge Extraction
UseAdaVoxel: 0
Voxel.size: 0.6
# Voxel.size: 0.5
Voxel.eigen_ratio: 0.05
Plane.min_points_size: 30
Plane.normal_theta_min: 20
Plane.normal_theta_max: 170
Ransac.dis_threshold: 0.02
# Ransac.dis_threshold: 0.015
Edge.min_dis_threshold: 0.08
# Edge.min_dis_threshold: 0.05
